spring:
  job:
    schedule: 5000
  datasource:
    one:
      url: jdbc:h2:~/one
      username: sa
      password:
      driver-class-name: org.h2.Driver
    two:
      url: jdbc:h2:~/two
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2-console
  data-ram-migration:
    channel:
      save:
        format: JDBC
      batch-process:
        batchSize: 1
        recordsPerBatch: 50
      database:
        sparkConfig:
          fetchSize: 500
          numPartitions: 20
          master: "local[*]"
        source:
          url: "jdbc:h2:~/source"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: source_emp
          schema:
          columns:
            - emp_id
            - emp_name
            - sal
        target:
          url: "jdbc:h2:~/target"
          user: sa
          password:
          driver: org.h2.Driver
          dbtable: target_emp
          schema:
          columns:
            - emp_id
            - emp_name
            - salary


